name: netafim_mobile
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+22

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  go_router: ^6.0.2
  flutter_svg: ^1.1.6
  json_annotation: ^4.8.0
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  freezed: ^2.3.5
  shared_preferences: ^2.0.15
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.2
  retrofit: ^4.0.1
  dio: ^5.0.1
  pretty_dio_logger: ^1.1.1
  get: ^4.6.1
  url_launcher: ^6.0.20
  recase: ^4.0.0
  fluttertoast: ^8.2.2
  http: ^0.13.3
  cached_network_image: ^3.1.0
  flutter_styled_toast: ^2.0.0
  expandable: ^5.0.1
  data_table_2: ^2.3.9
  package_info_plus: ^3.0.2
  firebase_core: ^2.9.0
  firebase_remote_config: ^4.0.0
  latlong2: ^0.8.1
  page_transition: ^2.0.2
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  flutter_barcode_scanner: ^2.0.0
  flutter_switch: ^0.3.2
  flutter_map: ^3.1.0
  maps_toolkit: ^2.0.1
  fl_chart: ^0.41.0
  map_launcher: ^2.5.0+1
  dropdown_button2: ^2.0.0
  signalr_netcore: ^1.3.3
  stack_trace: ^1.11.0
  maps_launcher: ^2.2.0
  webview_flutter: ^3.0.2
  syncfusion_flutter_charts: ^22.1.37
  flutter_carousel_widget: ^1.2.0
  zoom_widget: ^2.0.1
  flutter_localizations: 
    sdk: flutter
  intl: any


flutter_icons:
  image_path: "assets/images/app_icon.png"
  android: true
  ios: true

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  retrofit_generator: ^5.0.0
  change_app_package_name: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/devices/
#    - assets/fonts/
    - assets/data/
    - assets/data/australia.json


  fonts:
    - family: "Roboto"
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
